[package]
name = "Rust_SC_Chat"
version = "0.1.0"
authors = ["Kirill Ivanov <bragov4ik@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
